# taken from https://dev.to/abulka/comment/1dh3k thanks!
name: Release Catalyst
on:
  push:
    branches:
      [ "master" ]
jobs:
  release:
    runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.5.0
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Publish to release using Electron Forge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish